spring:
  application:
    name: springhomework

  datasource:
    url: jdbc:mysql://localhost:3306/springhomework
    username: likelionhw
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true